# Generated by Django 5.0.3 on 2024-03-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_comments_id_alter_listing_id_alter_user_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
    ]
